(() => {
  const API='https://naqnroehsuaex0o-dev.adb.ap-hyderabad-1.oraclecloudapps.com/ords/mahesh/tradingjournal';
  const TRADED=new Set(['WIN','LOSS','BREAKEVEN']); let entries=[],calendarCursor=new Date(),analysisMode='daily';
  const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0);
  const date=d=>new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric'}).format(new Date(d));
  const datetime=d=>new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(d));
  const cls=n=>n>0?'positive':n<0?'negative':'neutral';
  const outcomeClass=o=>String(o).split(' ')[0];
  function net(e){if(!TRADED.has(e.trade_result))return 0;const p=Math.abs(Number(e.pl)||0),c=Math.abs(Number(e.charges)||0);return (e.trade_result==='WIN'?p:e.trade_result==='LOSS'?-p:0)-c}
  const dayKey=e=>String(e.trade_on).slice(0,10);
  const keyDate=k=>new Date(`${k}T12:00:00`);
  const shortMoney=n=>`${n<0?'-':''}₹${Math.abs(n)>=1000?(Math.abs(n)/1000).toFixed(1)+'k':Math.round(Math.abs(n))}`;
  function archiveVisible(e){const filter=$('#archive-filter')?.value||'ACTIVE';return filter==='ALL'||(filter==='ARCHIVED'?e.archived==='Y':e.archived!=='Y')}
  function filtered(){const n=Number($('#period').value),base=entries.filter(archiveVisible);return n?base.filter(e=>new Date(e.trade_on)>=Date.now()-n*864e5):base}
  function ordered(xs){return [...xs].sort((a,b)=>new Date(b.trade_on)-new Date(a.trade_on))}
  function setStatus(text,kind=''){const el=$('#connection');el.textContent=text;el.className=`connection ${kind}`}
  async function loadAll(){if(location.protocol==='file:'){setStatus('Open this app from an HTTPS web address to connect to your journal.', 'error');return}setStatus('Syncing your trading journal…');let offset=0,all=[];try{while(true){const r=await fetch(`${API}/getTrades?offset=${offset}`,{headers:{Accept:'application/json'}});if(!r.ok)throw Error(`Server returned ${r.status}`);const page=await r.json();all=all.concat(page.items||[]);if(!page.hasMore)break;offset=Number(page.offset||offset)+(page.limit||25)}entries=all;if(all.length)calendarCursor=keyDate(ordered(all)[0].trade_on.slice(0,10));setStatus(`${entries.length} entries synced`, 'online');render()}catch(err){setStatus(`Could not connect: ${err.message}`, 'error');render()}}
  function screen(name){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));$('#title').textContent=({overview:'Overview',trades:'Trade log',calendar:'Calendar',journal:'Journal',entry:$('#entry-id').value?'Edit entry':'Log trade'})[name];if(name==='entry'&&!$('#entry-id').value){$('#trade-date').value=new Date().toISOString().slice(0,16);$('#form-mode').textContent='New entry'}window.scrollTo({top:0,behavior:'smooth'})}
  function render(){dashboard();trades();calendar();journal()}
  function dashboard(){const list=filtered(),trades=list.filter(e=>TRADED.has(e.trade_result)),pnl=trades.reduce((s,e)=>s+net(e),0),wins=trades.filter(e=>e.trade_result==='WIN').length,charges=trades.reduce((s,e)=>s+Math.abs(Number(e.charges)||0),0),rate=trades.length?Math.round(100*wins/trades.length):0;
    $('#stats').innerHTML=`<article class="stat"><label>Net P&amp;L</label><b class="${cls(pnl)}">${money(pnl)}</b><small>after charges</small></article><article class="stat"><label>Win rate</label><b>${rate}%</b><small>${wins} of ${trades.length} wins</small></article><article class="stat"><label>Trades</label><b>${trades.length}</b><small>${list.length-trades.length} observations</small></article><article class="stat"><label>Charges</label><b class="negative">${money(charges)}</b><small>total paid</small></article>`;
    $('#net-total').textContent=`${pnl>=0?'+':''}${money(pnl)}`;$('#net-total').className=cls(pnl);equity(trades);const rec=ordered(list).slice(0,5);$('#recent').innerHTML=rec.length?rec.map(row).join(''):empty('No trades found.');}
  function row(e){return `<button class="recent-row trade-open" data-id="${e.id}"><span class="entry-main"><span class="outcome ${outcomeClass(e.trade_result)}">${esc(e.trade_result)}</span><span class="snippet">${esc(e.notes||'No reflection')}</span></span><span class="entry-side"><b class="${cls(net(e))}">${TRADED.has(e.trade_result)?money(net(e)):'—'}</b><span class="date">${date(e.trade_on)}</span></span></button>`}
  function equity(list){const el=$('#equity');if(!list.length){el.innerHTML=empty('Your performance curve will appear here.');return}const values=[...list].sort((a,b)=>new Date(a.trade_on)-new Date(b.trade_on)).map((e,i,a)=>({e,y:a.slice(0,i+1).reduce((s,x)=>s+net(x),0),i})),w=600,h=190,L=46,R=8,T=12,B=26,min=Math.min(0,...values.map(x=>x.y)),max=Math.max(0,...values.map(x=>x.y)),span=max-min||1,x=i=>L+i*(w-L-R)/Math.max(values.length-1,1),y=v=>T+(max-v)*(h-T-B)/span,marks=[min,(min+max)/2,max].map(v=>`<line class="grid" x1="${L}" x2="${w-R}" y1="${y(v)}" y2="${y(v)}"/><text x="${L-7}" y="${y(v)+4}" text-anchor="end">${Math.round(v/1000)}k</text>`).join(''),line=values.map((v,i)=>`${i?'L':'M'}${x(v.i)},${y(v.y)}`).join(' '),area=`M${x(0)},${y(0)} ${values.map(v=>`L${x(v.i)},${y(v.y)}`).join(' ')} L${x(values.length-1)},${y(0)} Z`;el.innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Cumulative net profit and loss"><title>Cumulative net profit and loss</title>${marks}<path class="area" d="${area}"/><path class="line" d="${line}"/><text x="${L}" y="${h-5}">${date(values[0].e.trade_on)}</text><text x="${w-R}" y="${h-5}" text-anchor="end">${date(values.at(-1).e.trade_on)}</text></svg>`}
  function calendar(){const live=entries.filter(e=>e.archived!=='Y'),month=calendarCursor.getMonth(),year=calendarCursor.getFullYear(),byDay=new Map();live.forEach(e=>{const key=dayKey(e),item=byDay.get(key)||{total:0,count:0};item.total+=net(e);item.count++;byDay.set(key,item)});$('#calendar-label').textContent=new Intl.DateTimeFormat('en-IN',{month:'long',year:'numeric'}).format(calendarCursor);const first=(new Date(year,month,1).getDay()+6)%7,last=new Date(year,month+1,0).getDate(),cells=[];for(let i=0;i<first;i++)cells.push('<span class="cal-blank"></span>');for(let d=1;d<=last;d++){const key=`${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,item=byDay.get(key),total=item?.total||0;cells.push(`<button class="cal-day ${item?cls(total):''}" ${item?`data-calendar-day="${key}"`:''}><span>${d}</span>${item?`<b>${shortMoney(total)}</b>`:'<i>—</i>'}</button>`)}$('#calendar-grid').innerHTML=cells.join('');const groups=periodGroups(analysisMode,live),total=groups.reduce((s,g)=>s+g.total,0),names={daily:'Daily',weekly:'Weekly',monthly:'Monthly'};$('#analysis-kicker').textContent=`${names[analysisMode]} performance`;$('#analysis-title').textContent=`${names[analysisMode]} net P&L`;$('#analysis-total').textContent=`${total>=0?'+':''}${money(total)}`;$('#analysis-total').className=cls(total);document.querySelectorAll('.analysis-tab').forEach(b=>b.classList.toggle('active',b.dataset.analysis===analysisMode));renderBars(groups);$('#period-list').innerHTML=groups.length?groups.slice(0,12).map(g=>`<div class="period-row"><span>${g.label}<small>${g.count} ${g.count===1?'entry':'entries'}</small></span><b class="${cls(g.total)}">${money(g.total)}</b></div>`).join(''):empty('No active entries to show.');}
  function periodGroups(mode,list){const map=new Map();list.forEach(e=>{const d=keyDate(dayKey(e));let key,label;if(mode==='daily'){key=dayKey(e);label=new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short'}).format(d)}else if(mode==='weekly'){const start=new Date(d);start.setDate(d.getDate()-((d.getDay()+6)%7));key=start.toISOString().slice(0,10);label=`Week of ${new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short'}).format(start)}`}else{key=dayKey(e).slice(0,7);label=new Intl.DateTimeFormat('en-IN',{month:'short',year:'numeric'}).format(d)}const item=map.get(key)||{key,label,total:0,count:0};item.total+=net(e);item.count++;map.set(key,item)});return [...map.values()].sort((a,b)=>b.key.localeCompare(a.key))}
  function renderBars(groups){const show=groups.slice(0,10).reverse(),max=Math.max(1,...show.map(g=>Math.abs(g.total)));$('#analysis-chart').innerHTML=show.length?show.map(g=>`<div class="bar-col"><div class="bar-track"><span class="bar ${cls(g.total)}" style="height:${Math.max(5,Math.round(Math.abs(g.total)/max*100))}%" title="${esc(g.label)}: ${money(g.total)}"></span></div><small>${esc(g.label.replace('Week of ',''))}</small></div>`).join(''):empty('No chart data.')}
  function trades(){const outcome=$('#outcome-filter').value,term=$('#search').value.toLowerCase(),list=ordered(entries.filter(e=>archiveVisible(e)&&(outcome==='ALL'||e.trade_result===outcome)&&`${e.notes} ${e.trade_rules}`.toLowerCase().includes(term)));$('#trade-list').innerHTML=list.length?list.map(e=>`<button class="trade-row trade-open" data-id="${e.id}"><span class="entry-main"><span class="outcome ${outcomeClass(e.trade_result)}">${esc(e.trade_result)}</span><span class="trade-meta">${date(e.trade_on)} · ${esc((e.notes||'No reflection').replace(/\s+/g,' ').slice(0,58))}</span></span><span class="entry-side"><b class="${cls(net(e))}">${TRADED.has(e.trade_result)?money(net(e)):'—'}</b><span class="date">Net result</span></span></button>`).join(''):empty('No matching entries.')}
  function journal(){const term=$('#journal-search').value.toLowerCase(),list=ordered(entries.filter(e=>archiveVisible(e)&&`${e.notes} ${e.trade_rules}`.toLowerCase().includes(term)));$('#journal-list').innerHTML=list.length?list.map(e=>`<button class="journal-card trade-open" data-id="${e.id}"><span class="outcome ${outcomeClass(e.trade_result)}">${esc(e.trade_result)} · ${date(e.trade_on)}</span><p>${esc(e.notes||'No reflection')}</p></button>`).join(''):empty('No reflections found.')}
  function empty(s){return `<div class="empty">${esc(s)}</div>`}
  async function detail(id){try{const r=await fetch(`${API}/getTrade/${id}`,{headers:{Accept:'application/json'}}),data=await r.json(),e=data.items?.[0]||data;if(!r.ok)throw Error('Could not load trade');showDetail(e)}catch{const e=entries.find(x=>String(x.id)===String(id));if(e)showDetail(e)}}
  function showDetail(e){const archived=e.archived==='Y';$('#detail-content').innerHTML=`<p class="kicker">${datetime(e.trade_on)} · ${esc(e.trade_result)}${archived?' · Archived':''}</p><h2 class="${cls(net(e))}">${TRADED.has(e.trade_result)?money(net(e))+' net':'Journal entry'}</h2><span class="detail-label">Reflection</span>${esc(e.notes||'No reflection recorded.')}<span class="detail-label">Rules / playbook</span>${esc(e.trade_rules||'No rules recorded.')}<p><button class="text-btn edit" data-id="${e.id}">Edit entry</button><button class="text-btn archive-toggle" data-id="${e.id}">${archived?'Restore entry':'Archive entry'}</button></p>`;$('#detail').showModal()}
  function edit(id){const e=entries.find(x=>String(x.id)===String(id));if(!e)return;$('#detail').close();$('#entry-id').value=e.id;$('#entry-archived').value=e.archived||'N';$('#trade-date').value=new Date(e.trade_on).toISOString().slice(0,16);$('#trade-outcome').value=e.trade_result;$('#trade-pnl').value=Math.abs(e.pl)||'';$('#trade-charges').value=Math.abs(e.charges)||0;$('#trade-notes').value=e.notes||'';$('#trade-rules').value=e.trade_rules||'';$('#form-mode').textContent='Edit entry';screen('entry')}
  async function toggleArchive(id){const e=entries.find(x=>String(x.id)===String(id));if(!e)return;const payload={trade_on:e.trade_on,trade_result:e.trade_result,pl:Math.abs(Number(e.pl)||0),charges:Math.abs(Number(e.charges)||0),notes:e.notes||'',trade_rules:e.trade_rules||'',archived:e.archived==='Y'?'N':'Y'};try{setStatus(payload.archived==='Y'?'Archiving entry…':'Restoring entry…');const r=await fetch(`${API}/getTrade/${id}`,{method:'PUT',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error(`Server returned ${r.status}`);$('#detail').close();await loadAll()}catch(err){setStatus(`Could not update entry: ${err.message}`, 'error')}}
  async function submit(event){event.preventDefault();const id=$('#entry-id').value,payload={trade_on:new Date($('#trade-date').value).toISOString(),trade_result:$('#trade-outcome').value,pl:Math.abs(Number($('#trade-pnl').value)||0),charges:Math.abs(Number($('#trade-charges').value)||0),notes:$('#trade-notes').value.trim(),trade_rules:$('#trade-rules').value.trim(),archived:$('#entry-archived').value||'N'},url=id?`${API}/getTrade/${id}`:`${API}/createTrade`,method=id?'PUT':'POST';try{setStatus('Saving entry…');const r=await fetch(url,{method,headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error(`Server returned ${r.status}`);$('#trade-form').reset();$('#entry-id').value='';setStatus('Saved. Syncing…','online');screen('overview');await loadAll()}catch(err){setStatus(`Save failed: ${err.message}`, 'error')}}
  document.addEventListener('click',e=>{const t=e.target.closest('[data-screen],[data-id]');if(!t)return;if(t.dataset.screen)screen(t.dataset.screen);if(t.classList.contains('trade-open'))detail(t.dataset.id);if(t.classList.contains('edit'))edit(t.dataset.id);if(t.classList.contains('archive-toggle'))toggleArchive(t.dataset.id)});$('#period').onchange=dashboard;$('#archive-filter').onchange=render;$('#outcome-filter').onchange=trades;$('#search').oninput=trades;$('#journal-search').oninput=journal;$('#refresh').onclick=loadAll;$('#trade-form').onsubmit=submit;$('#cancel').onclick=()=>{ $('#trade-form').reset();$('#entry-id').value='';screen('overview')};$('#close-detail').onclick=()=>$('#detail').close();$('#today').textContent=new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long'}).format(new Date());if(location.protocol==='http:'||location.protocol==='https:'){const link=document.createElement('link');link.rel='manifest';link.href='manifest.webmanifest';document.head.append(link);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js')}loadAll();
  $('#cal-prev').onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()-1,1);calendar()};
  $('#cal-next').onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,1);calendar()};
  document.querySelectorAll('.analysis-tab').forEach(button=>button.onclick=()=>{analysisMode=button.dataset.analysis;calendar()});
})();
