(() => {
  const STORE = 'trade-ledger-entries-v1';
  const TRADED = new Set(['WIN','LOSS','BREAKEVEN']);
  let entries = load();
  let selected = null;
  const $ = s => document.querySelector(s);
  const money = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n || 0);
  const shortDate = d => new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d));
  const dateTime = d => new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(d));
  const escape = s => String(s || '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function load(){try{return JSON.parse(localStorage.getItem(STORE)) || []}catch{return []}}
  function save(){localStorage.setItem(STORE,JSON.stringify(entries));render()}
  // The export records absolute values. Outcome supplies P&L direction; charges are always a cost.
  function gross(e){const amount=Math.abs(Number(e.pnl) || 0);return e.outcome==='WIN'?amount:e.outcome==='LOSS'?-amount:0}
  function net(e){return TRADED.has(e.outcome) ? gross(e) - Math.abs(Number(e.charges) || 0) : 0}
  function klass(v){return v > 0 ? 'positive' : v < 0 ? 'negative' : 'neutral'}
  function page(name){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===name));$('#page-title').textContent=({dashboard:'Overview',trades:'Trade log',journal:'Journal',new:$('#entry-id').value?'Edit entry':'Log trade'})[name];if(name==='new'&&!$('#entry-id').value)$('#trade-date').value=new Date().toISOString().slice(0,16);window.scrollTo({top:0,behavior:'smooth'})}
  function viewEntries(){const days=Number($('#period').value);if(!days)return entries;const cut=Date.now()-days*864e5;return entries.filter(e=>new Date(e.date).getTime()>=cut)}
  function ordered(list){return [...list].sort((a,b)=>new Date(b.date)-new Date(a.date))}
  function render(){renderDashboard();renderTrades();renderJournal()}
  function renderDashboard(){
    const all=viewEntries(), trades=all.filter(e=>TRADED.has(e.outcome)), wins=trades.filter(e=>e.outcome==='WIN'), pnl=trades.reduce((sum,e)=>sum+net(e),0), charges=trades.reduce((sum,e)=>sum+(Number(e.charges)||0),0), rate=trades.length?wins.length/trades.length*100:0;
    $('#stats').innerHTML=`<article class="stat"><label>Net P&amp;L</label><strong class="${klass(pnl)}">${money(pnl)}</strong><small>After ${money(charges)} charges</small></article><article class="stat"><label>Win rate</label><strong>${rate.toFixed(0)}%</strong><small>${wins.length} wins · ${trades.length-wins.length} non-wins</small></article><article class="stat"><label>Trades taken</label><strong>${trades.length}</strong><small>${all.length-trades.length} observations logged</small></article><article class="stat"><label>Avg. net / trade</label><strong class="${klass(trades.length?pnl/trades.length:0)}">${money(trades.length?pnl/trades.length:0)}</strong><small>Measured entries only</small></article>`;
    $('#equity-total').textContent=`${pnl>=0?'+':''}${money(pnl)} net`;
    drawEquity(trades);drawOutcomes(all);
    const journaled=all.filter(e=>e.notes&&e.notes.trim()).length, coverage=all.length?Math.round(journaled/all.length*100):0;
    $('#discipline').innerHTML=`<div class="discipline-num">${coverage}%</div><p class="discipline-copy">${journaled} of ${all.length} entries include a written reflection.</p><p class="muted">The quality of a trading system improves when the decision is recorded, not only the result.</p>`;
    const last=ordered(all).slice(0,5);$('#recent').innerHTML=last.length?last.map(row).join(''):empty();
  }
  function row(e){return `<div class="recent-row"><span class="trade-date">${shortDate(e.date)}</span><span class="note-preview">${escape((e.notes||'No journal note').replace(/\s+/g,' ').slice(0,100))}</span><b class="amount ${klass(net(e))}">${TRADED.has(e.outcome)?money(net(e)):'—'}</b><span class="outcome ${e.outcome.split(' ')[0]}">${escape(e.outcome)}</span></div>`}
  function drawEquity(trades){const host=$('#equity-chart');if(!trades.length){host.innerHTML=empty('Import your export or log a completed trade to see the curve.');return}const data=[...trades].sort((a,b)=>new Date(a.date)-new Date(b.date)).map((e,i,a)=>({e,x:i,y:a.slice(0,i+1).reduce((s,v)=>s+net(v),0)}));const w=720,h=280,p={l:58,r:14,t:16,b:35}, min=Math.min(0,...data.map(d=>d.y)),max=Math.max(0,...data.map(d=>d.y)),span=max-min||1,x=i=>p.l+i*(w-p.l-p.r)/Math.max(1,data.length-1),y=v=>p.t+(max-v)*(h-p.t-p.b)/span;const grid=[min,(min+max)/2,max].map(v=>`<line class="grid" x1="${p.l}" x2="${w-p.r}" y1="${y(v)}" y2="${y(v)}"/><text x="${p.l-8}" y="${y(v)+4}" text-anchor="end">${Math.round(v/1000)}k</text>`).join('');const path=data.map((d,i)=>`${i?'L':'M'}${x(d.x)},${y(d.y)}`).join(' ');const area=`M${x(0)},${y(0)} ${data.map(d=>`L${x(d.x)},${y(d.y)}`).join(' ')} L${x(data.length-1)},${y(0)} Z`;host.innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img"><title>Cumulative net profit and loss</title>${grid}<line class="axis" x1="${p.l}" x2="${w-p.r}" y1="${y(0)}" y2="${y(0)}"/><path class="area" d="${area}"/><path class="line" d="${path}"/>${data.map(d=>`<circle class="dotmark" cx="${x(d.x)}" cy="${y(d.y)}" r="4"><title>${dateTime(d.e.date)}: ${money(d.y)} cumulative</title></circle>`).join('')}<text x="${p.l}" y="${h-8}">${shortDate(data[0].e.date)}</text><text x="${w-p.r}" y="${h-8}" text-anchor="end">${shortDate(data.at(-1).e.date)}</text></svg>`}
  function drawOutcomes(list){const kinds=['WIN','LOSS','BREAKEVEN','NO TRADE','MISSED OPPORTUNITY'],colors=['#47d49a','#ff7481','#f8c45c','#78aaff','#7083a3'],counts=kinds.map(k=>list.filter(e=>e.outcome===k).length),total=counts.reduce((a,b)=>a+b,0);if(!total){$('#outcome-chart').innerHTML=empty();return}let offset=0;const segments=counts.map((n,i)=>{const len=100*n/total,el=n?`<circle cx="75" cy="75" r="57" pathLength="100" stroke="${colors[i]}" stroke-dasharray="${len} ${100-len}" stroke-dashoffset="${-offset}"/>`:'';offset+=len;return el}).join('');$('#outcome-chart').innerHTML=`<svg class="donut" viewBox="0 0 150 150" role="img"><title>Outcome distribution</title><circle cx="75" cy="75" r="57" stroke="#253047"/><g>${segments}</g><text x="75" y="70" text-anchor="middle" fill="#e9edf5" font-size="28" font-weight="700">${total}</text><text x="75" y="90" text-anchor="middle" fill="#8d98aa" font-size="11">entries</text></svg><div class="legend">${kinds.map((k,i)=>`<span><i class="swatch" style="background:${colors[i]}"></i>${k.replace(' OPPORTUNITY','')} <b>${counts[i]}</b></span>`).join('')}</div>`}
  function renderTrades(){const outcome=$('#outcome-filter').value, term=$('#search').value.toLowerCase();const list=ordered(entries.filter(e=>(outcome==='ALL'||e.outcome===outcome)&&`${e.notes} ${e.rules}`.toLowerCase().includes(term)));$('#trade-table').innerHTML=list.length?`<table><thead><tr><th>Date</th><th>Outcome</th><th>Net P&amp;L</th><th>Charges</th><th>Journal</th><th></th></tr></thead><tbody>${list.map(e=>`<tr><td>${shortDate(e.date)}</td><td><span class="outcome ${e.outcome.split(' ')[0]}">${escape(e.outcome)}</span></td><td class="${klass(net(e))}">${TRADED.has(e.outcome)?money(net(e)):'—'}</td><td>${TRADED.has(e.outcome)?money(e.charges):'—'}</td><td class="table-note">${escape((e.notes||'—').replace(/\s+/g,' '))}</td><td><button class="row-action" data-open="${e.id}">View</button> <button class="row-action" data-edit="${e.id}">Edit</button></td></tr>`).join('')}</tbody></table>`:empty()}
  function renderJournal(){const term=$('#journal-search').value.toLowerCase(),list=ordered(entries.filter(e=>`${e.notes} ${e.rules} ${e.outcome}`.toLowerCase().includes(term)));$('#journal-list').innerHTML=list.length?list.map(e=>`<button class="journal-item" data-journal="${e.id}"><b>${shortDate(e.date)} · <span class="outcome ${e.outcome.split(' ')[0]}">${escape(e.outcome)}</span></b><span>${escape((e.notes||'No note').replace(/\s+/g,' ').slice(0,100))}</span></button>`).join(''):empty();if(selected&&!entries.find(e=>e.id===selected))selected=null;if(selected)showJournal(selected)}
  function showJournal(id){selected=id;const e=entries.find(x=>x.id===id);if(!e)return;$('#journal-detail').innerHTML=`<p class="eyebrow">${dateTime(e.date)} · ${escape(e.outcome)}</p><h3 class="${klass(net(e))}">${TRADED.has(e.outcome)?money(net(e))+' net':'Journal entry'}</h3><span class="detail-label">Reflection</span>${escape(e.notes||'No journal note.')}<span class="detail-label">Rules / playbook</span>${escape(e.rules||'No rules recorded.')}`}
  function showModal(id){const e=entries.find(x=>x.id===id);if(!e)return;$('#modal-content').innerHTML=`<p class="eyebrow">${dateTime(e.date)} · ${escape(e.outcome)}</p><h2 class="${klass(net(e))}">${TRADED.has(e.outcome)?money(net(e))+' net':'Journal entry'}</h2><span class="detail-label">Reflection</span>${escape(e.notes||'No journal note.')}<span class="detail-label">Rules / playbook</span>${escape(e.rules||'No rules recorded.')}`;$('#detail-modal').showModal()}
  function empty(message='Log a trade or import a CSV to get started.') {return `<div class="empty"><b>No entries yet</b><span>${message}</span></div>`}
  function csvRows(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
  function num(value){const cleaned=String(value||'').replace(/[^0-9.-]/g,'');return cleaned?Number(cleaned):0}
  function importCsv(file){const reader=new FileReader();reader.onload=()=>{try{const rows=csvRows(reader.result),head=rows.shift().map(x=>x.trim()),idx=label=>head.findIndex(h=>h.toLowerCase()===label.toLowerCase());const date=idx('When did I took trade'),outcome=idx('Did I earn or lose'),pnl=idx('The amount I earn or lose in the Trade'),charges=idx('Brokerage or Government Charges for the Trade'),notes=idx('My Trading Journal Notes for the Trade'),rules=idx('Trade rules i have set for the Trade');if([date,outcome,pnl,charges].some(x=>x<0))throw Error('Those headings do not match the supported export.');const imported=rows.map((r,i)=>({id:crypto.randomUUID?.()||`${Date.now()}-${i}`,date:new Date(r[date]).toISOString(),outcome:(r[outcome]||'').trim().toUpperCase(),pnl:num(r[pnl]),charges:num(r[charges]),notes:r[notes]||'',rules:r[rules]||''})).filter(e=>e.outcome&&e.date!=='Invalid Date');entries=[...entries,...imported];save();page('dashboard');alert(`${imported.length} entries imported.`)}catch(err){alert(`Could not import this CSV: ${err.message}`)}};reader.readAsText(file)}
  function exportData(){const blob=new Blob([JSON.stringify(entries,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='trade-ledger-backup.json';a.click();URL.revokeObjectURL(url)}
  function edit(id){const e=entries.find(x=>x.id===id);if(!e)return;$('#entry-id').value=e.id;$('#trade-date').value=new Date(e.date).toISOString().slice(0,16);$('#trade-outcome').value=e.outcome;$('#trade-pnl').value=e.pnl||'';$('#trade-charges').value=e.charges||0;$('#trade-notes').value=e.notes||'';$('#trade-rules').value=e.rules||'';page('new')}
  document.addEventListener('click',e=>{const target=e.target.closest('[data-page],[data-open],[data-edit],[data-journal]');if(!target)return;if(target.dataset.page)page(target.dataset.page);if(target.dataset.open)showModal(target.dataset.open);if(target.dataset.edit)edit(target.dataset.edit);if(target.dataset.journal)showJournal(target.dataset.journal)});
  $('#period').addEventListener('change',renderDashboard);$('#outcome-filter').addEventListener('change',renderTrades);$('#search').addEventListener('input',renderTrades);$('#journal-search').addEventListener('input',renderJournal);$('#import-btn').onclick=()=>$('#csv-input').click();$('#csv-input').onchange=e=>e.target.files[0]&&importCsv(e.target.files[0]);$('#export-btn').onclick=exportData;$('#modal-close').onclick=()=>$('#detail-modal').close();$('#cancel-edit').onclick=()=>{ $('#trade-form').reset();$('#entry-id').value='';page('dashboard')};
  $('#trade-form').addEventListener('submit',e=>{e.preventDefault();const id=$('#entry-id').value,entry={id:id||crypto.randomUUID?.()||String(Date.now()),date:new Date($('#trade-date').value).toISOString(),outcome:$('#trade-outcome').value,pnl:num($('#trade-pnl').value),charges:num($('#trade-charges').value),notes:$('#trade-notes').value.trim(),rules:$('#trade-rules').value.trim()};if(id)entries=entries.map(x=>x.id===id?entry:x);else entries.push(entry);$('#trade-form').reset();$('#entry-id').value='';save();page('dashboard')});
  $('#today').textContent=new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
})();
